### ISSUE TITLE
Design Fundraising Page

### ISSUE THREAD

**Issue by Giles-Aiden** [Giles-Aiden/VueEnterpriseSite#2]
https://wireframe.cc/KMSeBV

Convert wireframe to Vuesax page

**Comment by Jblack262** [comment]
This is a test? I need "help"...

**Comment by LukeDujmic** [comment]
Assign me to this issue

**Comment by Giles-Aiden** [comment]
Merged feature.

Great work @LukeDujmic ! Looks good on desktop and mobile.

Closing issue.
